// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "SienaPlusMessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace sienaplus {

namespace {

const ::google::protobuf::Descriptor* SienaPlusMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SienaPlusMessage_reflection_ = NULL;
const ::google::protobuf::Descriptor* SienaPlusMessage_subscription_t_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SienaPlusMessage_subscription_t_reflection_ = NULL;
const ::google::protobuf::Descriptor* SienaPlusMessage_subscription_t_constraint_t_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SienaPlusMessage_subscription_t_constraint_t_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* SienaPlusMessage_subscription_t_operator_t_descriptor_ = NULL;
const ::google::protobuf::Descriptor* SienaPlusMessage_notification_t_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SienaPlusMessage_notification_t_reflection_ = NULL;
const ::google::protobuf::Descriptor* SienaPlusMessage_notification_t_attribute_t_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SienaPlusMessage_notification_t_attribute_t_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* SienaPlusMessage_message_type_t_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* SienaPlusMessage_tag_type_t_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_SienaPlusMessage_2eproto() {
  protobuf_AddDesc_SienaPlusMessage_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "SienaPlusMessage.proto");
  GOOGLE_CHECK(file != NULL);
  SienaPlusMessage_descriptor_ = file->message_type(0);
  static const int SienaPlusMessage_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage, sender_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage, subscription_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage, notification_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage, unsubscription_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage, payload_),
  };
  SienaPlusMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SienaPlusMessage_descriptor_,
      SienaPlusMessage::default_instance_,
      SienaPlusMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SienaPlusMessage));
  SienaPlusMessage_subscription_t_descriptor_ = SienaPlusMessage_descriptor_->nested_type(0);
  static const int SienaPlusMessage_subscription_t_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_subscription_t, constraints_),
  };
  SienaPlusMessage_subscription_t_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SienaPlusMessage_subscription_t_descriptor_,
      SienaPlusMessage_subscription_t::default_instance_,
      SienaPlusMessage_subscription_t_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_subscription_t, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_subscription_t, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SienaPlusMessage_subscription_t));
  SienaPlusMessage_subscription_t_constraint_t_descriptor_ = SienaPlusMessage_subscription_t_descriptor_->nested_type(0);
  static const int SienaPlusMessage_subscription_t_constraint_t_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_subscription_t_constraint_t, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_subscription_t_constraint_t, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_subscription_t_constraint_t, operator__),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_subscription_t_constraint_t, value_),
  };
  SienaPlusMessage_subscription_t_constraint_t_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SienaPlusMessage_subscription_t_constraint_t_descriptor_,
      SienaPlusMessage_subscription_t_constraint_t::default_instance_,
      SienaPlusMessage_subscription_t_constraint_t_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_subscription_t_constraint_t, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_subscription_t_constraint_t, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SienaPlusMessage_subscription_t_constraint_t));
  SienaPlusMessage_subscription_t_operator_t_descriptor_ = SienaPlusMessage_subscription_t_descriptor_->enum_type(0);
  SienaPlusMessage_notification_t_descriptor_ = SienaPlusMessage_descriptor_->nested_type(1);
  static const int SienaPlusMessage_notification_t_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_notification_t, attributes_),
  };
  SienaPlusMessage_notification_t_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SienaPlusMessage_notification_t_descriptor_,
      SienaPlusMessage_notification_t::default_instance_,
      SienaPlusMessage_notification_t_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_notification_t, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_notification_t, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SienaPlusMessage_notification_t));
  SienaPlusMessage_notification_t_attribute_t_descriptor_ = SienaPlusMessage_notification_t_descriptor_->nested_type(0);
  static const int SienaPlusMessage_notification_t_attribute_t_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_notification_t_attribute_t, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_notification_t_attribute_t, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_notification_t_attribute_t, value_),
  };
  SienaPlusMessage_notification_t_attribute_t_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SienaPlusMessage_notification_t_attribute_t_descriptor_,
      SienaPlusMessage_notification_t_attribute_t::default_instance_,
      SienaPlusMessage_notification_t_attribute_t_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_notification_t_attribute_t, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_notification_t_attribute_t, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SienaPlusMessage_notification_t_attribute_t));
  SienaPlusMessage_message_type_t_descriptor_ = SienaPlusMessage_descriptor_->enum_type(0);
  SienaPlusMessage_tag_type_t_descriptor_ = SienaPlusMessage_descriptor_->enum_type(1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_SienaPlusMessage_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SienaPlusMessage_descriptor_, &SienaPlusMessage::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SienaPlusMessage_subscription_t_descriptor_, &SienaPlusMessage_subscription_t::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SienaPlusMessage_subscription_t_constraint_t_descriptor_, &SienaPlusMessage_subscription_t_constraint_t::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SienaPlusMessage_notification_t_descriptor_, &SienaPlusMessage_notification_t::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SienaPlusMessage_notification_t_attribute_t_descriptor_, &SienaPlusMessage_notification_t_attribute_t::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_SienaPlusMessage_2eproto() {
  delete SienaPlusMessage::default_instance_;
  delete SienaPlusMessage_reflection_;
  delete SienaPlusMessage_subscription_t::default_instance_;
  delete SienaPlusMessage_subscription_t_reflection_;
  delete SienaPlusMessage_subscription_t_constraint_t::default_instance_;
  delete SienaPlusMessage_subscription_t_constraint_t_reflection_;
  delete SienaPlusMessage_notification_t::default_instance_;
  delete SienaPlusMessage_notification_t_reflection_;
  delete SienaPlusMessage_notification_t_attribute_t::default_instance_;
  delete SienaPlusMessage_notification_t_attribute_t_reflection_;
}

void protobuf_AddDesc_SienaPlusMessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\026SienaPlusMessage.proto\022\tsienaplus\"\335\007\n\020"
    "SienaPlusMessage\0228\n\004type\030\001 \002(\0162*.sienapl"
    "us.SienaPlusMessage.message_type_t\022\016\n\006se"
    "nder\030\002 \002(\t\022@\n\014subscription\030\003 \001(\0132*.siena"
    "plus.SienaPlusMessage.subscription_t\022@\n\014"
    "notification\030\004 \001(\0132*.sienaplus.SienaPlus"
    "Message.notification_t\022\026\n\016unsubscription"
    "\030\005 \001(\t\022\017\n\007payload\030\006 \001(\t\032\227\003\n\016subscription"
    "_t\022L\n\013constraints\030\001 \003(\01327.sienaplus.Sien"
    "aPlusMessage.subscription_t.constraint_t"
    "\032\252\001\n\014constraint_t\0224\n\004type\030\001 \002(\0162&.sienap"
    "lus.SienaPlusMessage.tag_type_t\022\014\n\004name\030"
    "\002 \002(\t\022G\n\010operator\030\003 \002(\01625.sienaplus.Sien"
    "aPlusMessage.subscription_t.operator_t\022\r"
    "\n\005value\030\004 \002(\t\"\211\001\n\noperator_t\022\t\n\005EQUAL\020\001\022"
    "\r\n\tLESS_THAN\020\002\022\020\n\014GREATER_THAN\020\003\022\n\n\006SUFF"
    "IX\020\004\022\n\n\006PREFIX\020\005\022\016\n\nSUB_STRING\020\006\022\007\n\003ANY\020"
    "\007\022\r\n\tNOT_EQUAL\020\010\022\017\n\013REGULAR_EXP\020\t\032\276\001\n\016no"
    "tification_t\022J\n\nattributes\030\001 \003(\01326.siena"
    "plus.SienaPlusMessage.notification_t.att"
    "ribute_t\032`\n\013attribute_t\0224\n\004type\030\001 \002(\0162&."
    "sienaplus.SienaPlusMessage.tag_type_t\022\014\n"
    "\004name\030\002 \002(\t\022\r\n\005value\030\003 \002(\t\"-\n\016message_ty"
    "pe_t\022\007\n\003SUB\020\001\022\007\n\003NOT\020\002\022\t\n\005UNSUB\020\003\"H\n\ntag"
    "_type_t\022\n\n\006STRING\020\001\022\007\n\003INT\020\002\022\n\n\006DOUBLE\020\003"
    "\022\013\n\007BOOLEAN\020\004\022\014\n\010ANY_TYPE\020\005", 1027);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "SienaPlusMessage.proto", &protobuf_RegisterTypes);
  SienaPlusMessage::default_instance_ = new SienaPlusMessage();
  SienaPlusMessage_subscription_t::default_instance_ = new SienaPlusMessage_subscription_t();
  SienaPlusMessage_subscription_t_constraint_t::default_instance_ = new SienaPlusMessage_subscription_t_constraint_t();
  SienaPlusMessage_notification_t::default_instance_ = new SienaPlusMessage_notification_t();
  SienaPlusMessage_notification_t_attribute_t::default_instance_ = new SienaPlusMessage_notification_t_attribute_t();
  SienaPlusMessage::default_instance_->InitAsDefaultInstance();
  SienaPlusMessage_subscription_t::default_instance_->InitAsDefaultInstance();
  SienaPlusMessage_subscription_t_constraint_t::default_instance_->InitAsDefaultInstance();
  SienaPlusMessage_notification_t::default_instance_->InitAsDefaultInstance();
  SienaPlusMessage_notification_t_attribute_t::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_SienaPlusMessage_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_SienaPlusMessage_2eproto {
  StaticDescriptorInitializer_SienaPlusMessage_2eproto() {
    protobuf_AddDesc_SienaPlusMessage_2eproto();
  }
} static_descriptor_initializer_SienaPlusMessage_2eproto_;


// ===================================================================

const ::google::protobuf::EnumDescriptor* SienaPlusMessage_message_type_t_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SienaPlusMessage_message_type_t_descriptor_;
}
bool SienaPlusMessage_message_type_t_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const SienaPlusMessage_message_type_t SienaPlusMessage::SUB;
const SienaPlusMessage_message_type_t SienaPlusMessage::NOT;
const SienaPlusMessage_message_type_t SienaPlusMessage::UNSUB;
const SienaPlusMessage_message_type_t SienaPlusMessage::message_type_t_MIN;
const SienaPlusMessage_message_type_t SienaPlusMessage::message_type_t_MAX;
const int SienaPlusMessage::message_type_t_ARRAYSIZE;
#endif  // _MSC_VER
const ::google::protobuf::EnumDescriptor* SienaPlusMessage_tag_type_t_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SienaPlusMessage_tag_type_t_descriptor_;
}
bool SienaPlusMessage_tag_type_t_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const SienaPlusMessage_tag_type_t SienaPlusMessage::STRING;
const SienaPlusMessage_tag_type_t SienaPlusMessage::INT;
const SienaPlusMessage_tag_type_t SienaPlusMessage::DOUBLE;
const SienaPlusMessage_tag_type_t SienaPlusMessage::BOOLEAN;
const SienaPlusMessage_tag_type_t SienaPlusMessage::ANY_TYPE;
const SienaPlusMessage_tag_type_t SienaPlusMessage::tag_type_t_MIN;
const SienaPlusMessage_tag_type_t SienaPlusMessage::tag_type_t_MAX;
const int SienaPlusMessage::tag_type_t_ARRAYSIZE;
#endif  // _MSC_VER
const ::google::protobuf::EnumDescriptor* SienaPlusMessage_subscription_t_operator_t_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SienaPlusMessage_subscription_t_operator_t_descriptor_;
}
bool SienaPlusMessage_subscription_t_operator_t_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const SienaPlusMessage_subscription_t_operator_t SienaPlusMessage_subscription_t::EQUAL;
const SienaPlusMessage_subscription_t_operator_t SienaPlusMessage_subscription_t::LESS_THAN;
const SienaPlusMessage_subscription_t_operator_t SienaPlusMessage_subscription_t::GREATER_THAN;
const SienaPlusMessage_subscription_t_operator_t SienaPlusMessage_subscription_t::SUFFIX;
const SienaPlusMessage_subscription_t_operator_t SienaPlusMessage_subscription_t::PREFIX;
const SienaPlusMessage_subscription_t_operator_t SienaPlusMessage_subscription_t::SUB_STRING;
const SienaPlusMessage_subscription_t_operator_t SienaPlusMessage_subscription_t::ANY;
const SienaPlusMessage_subscription_t_operator_t SienaPlusMessage_subscription_t::NOT_EQUAL;
const SienaPlusMessage_subscription_t_operator_t SienaPlusMessage_subscription_t::REGULAR_EXP;
const SienaPlusMessage_subscription_t_operator_t SienaPlusMessage_subscription_t::operator_t_MIN;
const SienaPlusMessage_subscription_t_operator_t SienaPlusMessage_subscription_t::operator_t_MAX;
const int SienaPlusMessage_subscription_t::operator_t_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int SienaPlusMessage_subscription_t_constraint_t::kTypeFieldNumber;
const int SienaPlusMessage_subscription_t_constraint_t::kNameFieldNumber;
const int SienaPlusMessage_subscription_t_constraint_t::kOperatorFieldNumber;
const int SienaPlusMessage_subscription_t_constraint_t::kValueFieldNumber;
#endif  // !_MSC_VER

SienaPlusMessage_subscription_t_constraint_t::SienaPlusMessage_subscription_t_constraint_t()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SienaPlusMessage_subscription_t_constraint_t::InitAsDefaultInstance() {
}

SienaPlusMessage_subscription_t_constraint_t::SienaPlusMessage_subscription_t_constraint_t(const SienaPlusMessage_subscription_t_constraint_t& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SienaPlusMessage_subscription_t_constraint_t::SharedCtor() {
  _cached_size_ = 0;
  type_ = 1;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  operator__ = 1;
  value_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SienaPlusMessage_subscription_t_constraint_t::~SienaPlusMessage_subscription_t_constraint_t() {
  SharedDtor();
}

void SienaPlusMessage_subscription_t_constraint_t::SharedDtor() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (value_ != &::google::protobuf::internal::kEmptyString) {
    delete value_;
  }
  if (this != default_instance_) {
  }
}

void SienaPlusMessage_subscription_t_constraint_t::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SienaPlusMessage_subscription_t_constraint_t::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SienaPlusMessage_subscription_t_constraint_t_descriptor_;
}

const SienaPlusMessage_subscription_t_constraint_t& SienaPlusMessage_subscription_t_constraint_t::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_SienaPlusMessage_2eproto();  return *default_instance_;
}

SienaPlusMessage_subscription_t_constraint_t* SienaPlusMessage_subscription_t_constraint_t::default_instance_ = NULL;

SienaPlusMessage_subscription_t_constraint_t* SienaPlusMessage_subscription_t_constraint_t::New() const {
  return new SienaPlusMessage_subscription_t_constraint_t;
}

void SienaPlusMessage_subscription_t_constraint_t::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    type_ = 1;
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
      }
    }
    operator__ = 1;
    if (has_value()) {
      if (value_ != &::google::protobuf::internal::kEmptyString) {
        value_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SienaPlusMessage_subscription_t_constraint_t::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .sienaplus.SienaPlusMessage.tag_type_t type = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::sienaplus::SienaPlusMessage_tag_type_t_IsValid(value)) {
            set_type(static_cast< ::sienaplus::SienaPlusMessage_tag_type_t >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_name;
        break;
      }
      
      // required string name = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_operator;
        break;
      }
      
      // required .sienaplus.SienaPlusMessage.subscription_t.operator_t operator = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_operator:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::sienaplus::SienaPlusMessage_subscription_t_operator_t_IsValid(value)) {
            set_operator_(static_cast< ::sienaplus::SienaPlusMessage_subscription_t_operator_t >(value));
          } else {
            mutable_unknown_fields()->AddVarint(3, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_value;
        break;
      }
      
      // required string value = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_value:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_value()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->value().data(), this->value().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SienaPlusMessage_subscription_t_constraint_t::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .sienaplus.SienaPlusMessage.tag_type_t type = 1;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }
  
  // required string name = 2;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->name(), output);
  }
  
  // required .sienaplus.SienaPlusMessage.subscription_t.operator_t operator = 3;
  if (has_operator_()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->operator_(), output);
  }
  
  // required string value = 4;
  if (has_value()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->value().data(), this->value().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->value(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SienaPlusMessage_subscription_t_constraint_t::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .sienaplus.SienaPlusMessage.tag_type_t type = 1;
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }
  
  // required string name = 2;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->name(), target);
  }
  
  // required .sienaplus.SienaPlusMessage.subscription_t.operator_t operator = 3;
  if (has_operator_()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->operator_(), target);
  }
  
  // required string value = 4;
  if (has_value()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->value().data(), this->value().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->value(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SienaPlusMessage_subscription_t_constraint_t::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .sienaplus.SienaPlusMessage.tag_type_t type = 1;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
    }
    
    // required string name = 2;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }
    
    // required .sienaplus.SienaPlusMessage.subscription_t.operator_t operator = 3;
    if (has_operator_()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->operator_());
    }
    
    // required string value = 4;
    if (has_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->value());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SienaPlusMessage_subscription_t_constraint_t::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SienaPlusMessage_subscription_t_constraint_t* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SienaPlusMessage_subscription_t_constraint_t*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SienaPlusMessage_subscription_t_constraint_t::MergeFrom(const SienaPlusMessage_subscription_t_constraint_t& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_operator_()) {
      set_operator_(from.operator_());
    }
    if (from.has_value()) {
      set_value(from.value());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SienaPlusMessage_subscription_t_constraint_t::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SienaPlusMessage_subscription_t_constraint_t::CopyFrom(const SienaPlusMessage_subscription_t_constraint_t& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SienaPlusMessage_subscription_t_constraint_t::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;
  
  return true;
}

void SienaPlusMessage_subscription_t_constraint_t::Swap(SienaPlusMessage_subscription_t_constraint_t* other) {
  if (other != this) {
    std::swap(type_, other->type_);
    std::swap(name_, other->name_);
    std::swap(operator__, other->operator__);
    std::swap(value_, other->value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SienaPlusMessage_subscription_t_constraint_t::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SienaPlusMessage_subscription_t_constraint_t_descriptor_;
  metadata.reflection = SienaPlusMessage_subscription_t_constraint_t_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int SienaPlusMessage_subscription_t::kConstraintsFieldNumber;
#endif  // !_MSC_VER

SienaPlusMessage_subscription_t::SienaPlusMessage_subscription_t()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SienaPlusMessage_subscription_t::InitAsDefaultInstance() {
}

SienaPlusMessage_subscription_t::SienaPlusMessage_subscription_t(const SienaPlusMessage_subscription_t& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SienaPlusMessage_subscription_t::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SienaPlusMessage_subscription_t::~SienaPlusMessage_subscription_t() {
  SharedDtor();
}

void SienaPlusMessage_subscription_t::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SienaPlusMessage_subscription_t::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SienaPlusMessage_subscription_t::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SienaPlusMessage_subscription_t_descriptor_;
}

const SienaPlusMessage_subscription_t& SienaPlusMessage_subscription_t::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_SienaPlusMessage_2eproto();  return *default_instance_;
}

SienaPlusMessage_subscription_t* SienaPlusMessage_subscription_t::default_instance_ = NULL;

SienaPlusMessage_subscription_t* SienaPlusMessage_subscription_t::New() const {
  return new SienaPlusMessage_subscription_t;
}

void SienaPlusMessage_subscription_t::Clear() {
  constraints_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SienaPlusMessage_subscription_t::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .sienaplus.SienaPlusMessage.subscription_t.constraint_t constraints = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_constraints:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_constraints()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_constraints;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SienaPlusMessage_subscription_t::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .sienaplus.SienaPlusMessage.subscription_t.constraint_t constraints = 1;
  for (int i = 0; i < this->constraints_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->constraints(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SienaPlusMessage_subscription_t::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .sienaplus.SienaPlusMessage.subscription_t.constraint_t constraints = 1;
  for (int i = 0; i < this->constraints_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->constraints(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SienaPlusMessage_subscription_t::ByteSize() const {
  int total_size = 0;
  
  // repeated .sienaplus.SienaPlusMessage.subscription_t.constraint_t constraints = 1;
  total_size += 1 * this->constraints_size();
  for (int i = 0; i < this->constraints_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->constraints(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SienaPlusMessage_subscription_t::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SienaPlusMessage_subscription_t* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SienaPlusMessage_subscription_t*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SienaPlusMessage_subscription_t::MergeFrom(const SienaPlusMessage_subscription_t& from) {
  GOOGLE_CHECK_NE(&from, this);
  constraints_.MergeFrom(from.constraints_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SienaPlusMessage_subscription_t::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SienaPlusMessage_subscription_t::CopyFrom(const SienaPlusMessage_subscription_t& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SienaPlusMessage_subscription_t::IsInitialized() const {
  
  for (int i = 0; i < constraints_size(); i++) {
    if (!this->constraints(i).IsInitialized()) return false;
  }
  return true;
}

void SienaPlusMessage_subscription_t::Swap(SienaPlusMessage_subscription_t* other) {
  if (other != this) {
    constraints_.Swap(&other->constraints_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SienaPlusMessage_subscription_t::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SienaPlusMessage_subscription_t_descriptor_;
  metadata.reflection = SienaPlusMessage_subscription_t_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int SienaPlusMessage_notification_t_attribute_t::kTypeFieldNumber;
const int SienaPlusMessage_notification_t_attribute_t::kNameFieldNumber;
const int SienaPlusMessage_notification_t_attribute_t::kValueFieldNumber;
#endif  // !_MSC_VER

SienaPlusMessage_notification_t_attribute_t::SienaPlusMessage_notification_t_attribute_t()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SienaPlusMessage_notification_t_attribute_t::InitAsDefaultInstance() {
}

SienaPlusMessage_notification_t_attribute_t::SienaPlusMessage_notification_t_attribute_t(const SienaPlusMessage_notification_t_attribute_t& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SienaPlusMessage_notification_t_attribute_t::SharedCtor() {
  _cached_size_ = 0;
  type_ = 1;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  value_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SienaPlusMessage_notification_t_attribute_t::~SienaPlusMessage_notification_t_attribute_t() {
  SharedDtor();
}

void SienaPlusMessage_notification_t_attribute_t::SharedDtor() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (value_ != &::google::protobuf::internal::kEmptyString) {
    delete value_;
  }
  if (this != default_instance_) {
  }
}

void SienaPlusMessage_notification_t_attribute_t::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SienaPlusMessage_notification_t_attribute_t::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SienaPlusMessage_notification_t_attribute_t_descriptor_;
}

const SienaPlusMessage_notification_t_attribute_t& SienaPlusMessage_notification_t_attribute_t::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_SienaPlusMessage_2eproto();  return *default_instance_;
}

SienaPlusMessage_notification_t_attribute_t* SienaPlusMessage_notification_t_attribute_t::default_instance_ = NULL;

SienaPlusMessage_notification_t_attribute_t* SienaPlusMessage_notification_t_attribute_t::New() const {
  return new SienaPlusMessage_notification_t_attribute_t;
}

void SienaPlusMessage_notification_t_attribute_t::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    type_ = 1;
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
      }
    }
    if (has_value()) {
      if (value_ != &::google::protobuf::internal::kEmptyString) {
        value_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SienaPlusMessage_notification_t_attribute_t::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .sienaplus.SienaPlusMessage.tag_type_t type = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::sienaplus::SienaPlusMessage_tag_type_t_IsValid(value)) {
            set_type(static_cast< ::sienaplus::SienaPlusMessage_tag_type_t >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_name;
        break;
      }
      
      // required string name = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_value;
        break;
      }
      
      // required string value = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_value:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_value()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->value().data(), this->value().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SienaPlusMessage_notification_t_attribute_t::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .sienaplus.SienaPlusMessage.tag_type_t type = 1;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }
  
  // required string name = 2;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->name(), output);
  }
  
  // required string value = 3;
  if (has_value()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->value().data(), this->value().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->value(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SienaPlusMessage_notification_t_attribute_t::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .sienaplus.SienaPlusMessage.tag_type_t type = 1;
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }
  
  // required string name = 2;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->name(), target);
  }
  
  // required string value = 3;
  if (has_value()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->value().data(), this->value().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->value(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SienaPlusMessage_notification_t_attribute_t::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .sienaplus.SienaPlusMessage.tag_type_t type = 1;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
    }
    
    // required string name = 2;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }
    
    // required string value = 3;
    if (has_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->value());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SienaPlusMessage_notification_t_attribute_t::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SienaPlusMessage_notification_t_attribute_t* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SienaPlusMessage_notification_t_attribute_t*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SienaPlusMessage_notification_t_attribute_t::MergeFrom(const SienaPlusMessage_notification_t_attribute_t& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_value()) {
      set_value(from.value());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SienaPlusMessage_notification_t_attribute_t::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SienaPlusMessage_notification_t_attribute_t::CopyFrom(const SienaPlusMessage_notification_t_attribute_t& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SienaPlusMessage_notification_t_attribute_t::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;
  
  return true;
}

void SienaPlusMessage_notification_t_attribute_t::Swap(SienaPlusMessage_notification_t_attribute_t* other) {
  if (other != this) {
    std::swap(type_, other->type_);
    std::swap(name_, other->name_);
    std::swap(value_, other->value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SienaPlusMessage_notification_t_attribute_t::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SienaPlusMessage_notification_t_attribute_t_descriptor_;
  metadata.reflection = SienaPlusMessage_notification_t_attribute_t_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int SienaPlusMessage_notification_t::kAttributesFieldNumber;
#endif  // !_MSC_VER

SienaPlusMessage_notification_t::SienaPlusMessage_notification_t()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SienaPlusMessage_notification_t::InitAsDefaultInstance() {
}

SienaPlusMessage_notification_t::SienaPlusMessage_notification_t(const SienaPlusMessage_notification_t& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SienaPlusMessage_notification_t::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SienaPlusMessage_notification_t::~SienaPlusMessage_notification_t() {
  SharedDtor();
}

void SienaPlusMessage_notification_t::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SienaPlusMessage_notification_t::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SienaPlusMessage_notification_t::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SienaPlusMessage_notification_t_descriptor_;
}

const SienaPlusMessage_notification_t& SienaPlusMessage_notification_t::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_SienaPlusMessage_2eproto();  return *default_instance_;
}

SienaPlusMessage_notification_t* SienaPlusMessage_notification_t::default_instance_ = NULL;

SienaPlusMessage_notification_t* SienaPlusMessage_notification_t::New() const {
  return new SienaPlusMessage_notification_t;
}

void SienaPlusMessage_notification_t::Clear() {
  attributes_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SienaPlusMessage_notification_t::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .sienaplus.SienaPlusMessage.notification_t.attribute_t attributes = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_attributes:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_attributes()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_attributes;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SienaPlusMessage_notification_t::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .sienaplus.SienaPlusMessage.notification_t.attribute_t attributes = 1;
  for (int i = 0; i < this->attributes_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->attributes(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SienaPlusMessage_notification_t::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .sienaplus.SienaPlusMessage.notification_t.attribute_t attributes = 1;
  for (int i = 0; i < this->attributes_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->attributes(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SienaPlusMessage_notification_t::ByteSize() const {
  int total_size = 0;
  
  // repeated .sienaplus.SienaPlusMessage.notification_t.attribute_t attributes = 1;
  total_size += 1 * this->attributes_size();
  for (int i = 0; i < this->attributes_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->attributes(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SienaPlusMessage_notification_t::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SienaPlusMessage_notification_t* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SienaPlusMessage_notification_t*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SienaPlusMessage_notification_t::MergeFrom(const SienaPlusMessage_notification_t& from) {
  GOOGLE_CHECK_NE(&from, this);
  attributes_.MergeFrom(from.attributes_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SienaPlusMessage_notification_t::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SienaPlusMessage_notification_t::CopyFrom(const SienaPlusMessage_notification_t& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SienaPlusMessage_notification_t::IsInitialized() const {
  
  for (int i = 0; i < attributes_size(); i++) {
    if (!this->attributes(i).IsInitialized()) return false;
  }
  return true;
}

void SienaPlusMessage_notification_t::Swap(SienaPlusMessage_notification_t* other) {
  if (other != this) {
    attributes_.Swap(&other->attributes_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SienaPlusMessage_notification_t::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SienaPlusMessage_notification_t_descriptor_;
  metadata.reflection = SienaPlusMessage_notification_t_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int SienaPlusMessage::kTypeFieldNumber;
const int SienaPlusMessage::kSenderFieldNumber;
const int SienaPlusMessage::kSubscriptionFieldNumber;
const int SienaPlusMessage::kNotificationFieldNumber;
const int SienaPlusMessage::kUnsubscriptionFieldNumber;
const int SienaPlusMessage::kPayloadFieldNumber;
#endif  // !_MSC_VER

SienaPlusMessage::SienaPlusMessage()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SienaPlusMessage::InitAsDefaultInstance() {
  subscription_ = const_cast< ::sienaplus::SienaPlusMessage_subscription_t*>(&::sienaplus::SienaPlusMessage_subscription_t::default_instance());
  notification_ = const_cast< ::sienaplus::SienaPlusMessage_notification_t*>(&::sienaplus::SienaPlusMessage_notification_t::default_instance());
}

SienaPlusMessage::SienaPlusMessage(const SienaPlusMessage& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SienaPlusMessage::SharedCtor() {
  _cached_size_ = 0;
  type_ = 1;
  sender_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  subscription_ = NULL;
  notification_ = NULL;
  unsubscription_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  payload_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SienaPlusMessage::~SienaPlusMessage() {
  SharedDtor();
}

void SienaPlusMessage::SharedDtor() {
  if (sender_ != &::google::protobuf::internal::kEmptyString) {
    delete sender_;
  }
  if (unsubscription_ != &::google::protobuf::internal::kEmptyString) {
    delete unsubscription_;
  }
  if (payload_ != &::google::protobuf::internal::kEmptyString) {
    delete payload_;
  }
  if (this != default_instance_) {
    delete subscription_;
    delete notification_;
  }
}

void SienaPlusMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SienaPlusMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SienaPlusMessage_descriptor_;
}

const SienaPlusMessage& SienaPlusMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_SienaPlusMessage_2eproto();  return *default_instance_;
}

SienaPlusMessage* SienaPlusMessage::default_instance_ = NULL;

SienaPlusMessage* SienaPlusMessage::New() const {
  return new SienaPlusMessage;
}

void SienaPlusMessage::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    type_ = 1;
    if (has_sender()) {
      if (sender_ != &::google::protobuf::internal::kEmptyString) {
        sender_->clear();
      }
    }
    if (has_subscription()) {
      if (subscription_ != NULL) subscription_->::sienaplus::SienaPlusMessage_subscription_t::Clear();
    }
    if (has_notification()) {
      if (notification_ != NULL) notification_->::sienaplus::SienaPlusMessage_notification_t::Clear();
    }
    if (has_unsubscription()) {
      if (unsubscription_ != &::google::protobuf::internal::kEmptyString) {
        unsubscription_->clear();
      }
    }
    if (has_payload()) {
      if (payload_ != &::google::protobuf::internal::kEmptyString) {
        payload_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SienaPlusMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .sienaplus.SienaPlusMessage.message_type_t type = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::sienaplus::SienaPlusMessage_message_type_t_IsValid(value)) {
            set_type(static_cast< ::sienaplus::SienaPlusMessage_message_type_t >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_sender;
        break;
      }
      
      // required string sender = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_sender:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_sender()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->sender().data(), this->sender().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_subscription;
        break;
      }
      
      // optional .sienaplus.SienaPlusMessage.subscription_t subscription = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_subscription:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_subscription()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_notification;
        break;
      }
      
      // optional .sienaplus.SienaPlusMessage.notification_t notification = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_notification:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_notification()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_unsubscription;
        break;
      }
      
      // optional string unsubscription = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_unsubscription:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_unsubscription()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->unsubscription().data(), this->unsubscription().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(50)) goto parse_payload;
        break;
      }
      
      // optional string payload = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_payload:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_payload()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->payload().data(), this->payload().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SienaPlusMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .sienaplus.SienaPlusMessage.message_type_t type = 1;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }
  
  // required string sender = 2;
  if (has_sender()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->sender().data(), this->sender().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->sender(), output);
  }
  
  // optional .sienaplus.SienaPlusMessage.subscription_t subscription = 3;
  if (has_subscription()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->subscription(), output);
  }
  
  // optional .sienaplus.SienaPlusMessage.notification_t notification = 4;
  if (has_notification()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->notification(), output);
  }
  
  // optional string unsubscription = 5;
  if (has_unsubscription()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->unsubscription().data(), this->unsubscription().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      5, this->unsubscription(), output);
  }
  
  // optional string payload = 6;
  if (has_payload()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->payload().data(), this->payload().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      6, this->payload(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SienaPlusMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .sienaplus.SienaPlusMessage.message_type_t type = 1;
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }
  
  // required string sender = 2;
  if (has_sender()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->sender().data(), this->sender().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->sender(), target);
  }
  
  // optional .sienaplus.SienaPlusMessage.subscription_t subscription = 3;
  if (has_subscription()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->subscription(), target);
  }
  
  // optional .sienaplus.SienaPlusMessage.notification_t notification = 4;
  if (has_notification()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->notification(), target);
  }
  
  // optional string unsubscription = 5;
  if (has_unsubscription()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->unsubscription().data(), this->unsubscription().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->unsubscription(), target);
  }
  
  // optional string payload = 6;
  if (has_payload()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->payload().data(), this->payload().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->payload(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SienaPlusMessage::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .sienaplus.SienaPlusMessage.message_type_t type = 1;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
    }
    
    // required string sender = 2;
    if (has_sender()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->sender());
    }
    
    // optional .sienaplus.SienaPlusMessage.subscription_t subscription = 3;
    if (has_subscription()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->subscription());
    }
    
    // optional .sienaplus.SienaPlusMessage.notification_t notification = 4;
    if (has_notification()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->notification());
    }
    
    // optional string unsubscription = 5;
    if (has_unsubscription()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->unsubscription());
    }
    
    // optional string payload = 6;
    if (has_payload()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->payload());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SienaPlusMessage::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SienaPlusMessage* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SienaPlusMessage*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SienaPlusMessage::MergeFrom(const SienaPlusMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_sender()) {
      set_sender(from.sender());
    }
    if (from.has_subscription()) {
      mutable_subscription()->::sienaplus::SienaPlusMessage_subscription_t::MergeFrom(from.subscription());
    }
    if (from.has_notification()) {
      mutable_notification()->::sienaplus::SienaPlusMessage_notification_t::MergeFrom(from.notification());
    }
    if (from.has_unsubscription()) {
      set_unsubscription(from.unsubscription());
    }
    if (from.has_payload()) {
      set_payload(from.payload());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SienaPlusMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SienaPlusMessage::CopyFrom(const SienaPlusMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SienaPlusMessage::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  
  if (has_subscription()) {
    if (!this->subscription().IsInitialized()) return false;
  }
  if (has_notification()) {
    if (!this->notification().IsInitialized()) return false;
  }
  return true;
}

void SienaPlusMessage::Swap(SienaPlusMessage* other) {
  if (other != this) {
    std::swap(type_, other->type_);
    std::swap(sender_, other->sender_);
    std::swap(subscription_, other->subscription_);
    std::swap(notification_, other->notification_);
    std::swap(unsubscription_, other->unsubscription_);
    std::swap(payload_, other->payload_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SienaPlusMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SienaPlusMessage_descriptor_;
  metadata.reflection = SienaPlusMessage_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace sienaplus

// @@protoc_insertion_point(global_scope)
