// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "SienaPlusMessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace sienaplus {

namespace {

const ::google::protobuf::Descriptor* SienaPlusMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SienaPlusMessage_reflection_ = NULL;
const ::google::protobuf::Descriptor* SienaPlusMessage_value_t_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SienaPlusMessage_value_t_reflection_ = NULL;
const ::google::protobuf::Descriptor* SienaPlusMessage_subscription_t_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SienaPlusMessage_subscription_t_reflection_ = NULL;
const ::google::protobuf::Descriptor* SienaPlusMessage_subscription_t_constraint_t_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SienaPlusMessage_subscription_t_constraint_t_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* SienaPlusMessage_subscription_t_operator_t_descriptor_ = NULL;
const ::google::protobuf::Descriptor* SienaPlusMessage_notification_t_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SienaPlusMessage_notification_t_reflection_ = NULL;
const ::google::protobuf::Descriptor* SienaPlusMessage_notification_t_attribute_t_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SienaPlusMessage_notification_t_attribute_t_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* SienaPlusMessage_message_type_t_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* SienaPlusMessage_tag_type_t_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_SienaPlusMessage_2eproto() {
  protobuf_AddDesc_SienaPlusMessage_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "SienaPlusMessage.proto");
  GOOGLE_CHECK(file != NULL);
  SienaPlusMessage_descriptor_ = file->message_type(0);
  static const int SienaPlusMessage_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage, sender_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage, subscription_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage, notification_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage, unsubscription_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage, payload_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage, assigned_id_),
  };
  SienaPlusMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SienaPlusMessage_descriptor_,
      SienaPlusMessage::default_instance_,
      SienaPlusMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SienaPlusMessage));
  SienaPlusMessage_value_t_descriptor_ = SienaPlusMessage_descriptor_->nested_type(0);
  static const int SienaPlusMessage_value_t_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_value_t, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_value_t, string_value_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_value_t, int_value_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_value_t, double_value_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_value_t, bool_value_),
  };
  SienaPlusMessage_value_t_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SienaPlusMessage_value_t_descriptor_,
      SienaPlusMessage_value_t::default_instance_,
      SienaPlusMessage_value_t_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_value_t, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_value_t, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SienaPlusMessage_value_t));
  SienaPlusMessage_subscription_t_descriptor_ = SienaPlusMessage_descriptor_->nested_type(1);
  static const int SienaPlusMessage_subscription_t_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_subscription_t, constraints_),
  };
  SienaPlusMessage_subscription_t_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SienaPlusMessage_subscription_t_descriptor_,
      SienaPlusMessage_subscription_t::default_instance_,
      SienaPlusMessage_subscription_t_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_subscription_t, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_subscription_t, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SienaPlusMessage_subscription_t));
  SienaPlusMessage_subscription_t_constraint_t_descriptor_ = SienaPlusMessage_subscription_t_descriptor_->nested_type(0);
  static const int SienaPlusMessage_subscription_t_constraint_t_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_subscription_t_constraint_t, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_subscription_t_constraint_t, op_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_subscription_t_constraint_t, value_),
  };
  SienaPlusMessage_subscription_t_constraint_t_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SienaPlusMessage_subscription_t_constraint_t_descriptor_,
      SienaPlusMessage_subscription_t_constraint_t::default_instance_,
      SienaPlusMessage_subscription_t_constraint_t_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_subscription_t_constraint_t, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_subscription_t_constraint_t, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SienaPlusMessage_subscription_t_constraint_t));
  SienaPlusMessage_subscription_t_operator_t_descriptor_ = SienaPlusMessage_subscription_t_descriptor_->enum_type(0);
  SienaPlusMessage_notification_t_descriptor_ = SienaPlusMessage_descriptor_->nested_type(2);
  static const int SienaPlusMessage_notification_t_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_notification_t, attribute_),
  };
  SienaPlusMessage_notification_t_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SienaPlusMessage_notification_t_descriptor_,
      SienaPlusMessage_notification_t::default_instance_,
      SienaPlusMessage_notification_t_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_notification_t, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_notification_t, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SienaPlusMessage_notification_t));
  SienaPlusMessage_notification_t_attribute_t_descriptor_ = SienaPlusMessage_notification_t_descriptor_->nested_type(0);
  static const int SienaPlusMessage_notification_t_attribute_t_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_notification_t_attribute_t, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_notification_t_attribute_t, value_),
  };
  SienaPlusMessage_notification_t_attribute_t_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SienaPlusMessage_notification_t_attribute_t_descriptor_,
      SienaPlusMessage_notification_t_attribute_t::default_instance_,
      SienaPlusMessage_notification_t_attribute_t_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_notification_t_attribute_t, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SienaPlusMessage_notification_t_attribute_t, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SienaPlusMessage_notification_t_attribute_t));
  SienaPlusMessage_message_type_t_descriptor_ = SienaPlusMessage_descriptor_->enum_type(0);
  SienaPlusMessage_tag_type_t_descriptor_ = SienaPlusMessage_descriptor_->enum_type(1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_SienaPlusMessage_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SienaPlusMessage_descriptor_, &SienaPlusMessage::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SienaPlusMessage_value_t_descriptor_, &SienaPlusMessage_value_t::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SienaPlusMessage_subscription_t_descriptor_, &SienaPlusMessage_subscription_t::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SienaPlusMessage_subscription_t_constraint_t_descriptor_, &SienaPlusMessage_subscription_t_constraint_t::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SienaPlusMessage_notification_t_descriptor_, &SienaPlusMessage_notification_t::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SienaPlusMessage_notification_t_attribute_t_descriptor_, &SienaPlusMessage_notification_t_attribute_t::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_SienaPlusMessage_2eproto() {
  delete SienaPlusMessage::default_instance_;
  delete SienaPlusMessage_reflection_;
  delete SienaPlusMessage_value_t::default_instance_;
  delete SienaPlusMessage_value_t_reflection_;
  delete SienaPlusMessage_subscription_t::default_instance_;
  delete SienaPlusMessage_subscription_t_reflection_;
  delete SienaPlusMessage_subscription_t_constraint_t::default_instance_;
  delete SienaPlusMessage_subscription_t_constraint_t_reflection_;
  delete SienaPlusMessage_notification_t::default_instance_;
  delete SienaPlusMessage_notification_t_reflection_;
  delete SienaPlusMessage_notification_t_attribute_t::default_instance_;
  delete SienaPlusMessage_notification_t_attribute_t_reflection_;
}

void protobuf_AddDesc_SienaPlusMessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\026SienaPlusMessage.proto\022\tsienaplus\"\373\010\n\020"
    "SienaPlusMessage\0228\n\004type\030\001 \002(\0162*.sienapl"
    "us.SienaPlusMessage.message_type_t\022\016\n\006se"
    "nder\030\002 \002(\t\022@\n\014subscription\030\003 \001(\0132*.siena"
    "plus.SienaPlusMessage.subscription_t\022@\n\014"
    "notification\030\004 \001(\0132*.sienaplus.SienaPlus"
    "Message.notification_t\022\026\n\016unsubscription"
    "\030\005 \001(\t\022\017\n\007payload\030\006 \001(\t\022\023\n\013assigned_id\030\007"
    " \001(\005\032\222\001\n\007value_t\0224\n\004type\030\001 \002(\0162&.sienapl"
    "us.SienaPlusMessage.tag_type_t\022\024\n\014string"
    "_value\030\002 \001(\t\022\021\n\tint_value\030\003 \001(\005\022\024\n\014doubl"
    "e_value\030\004 \001(\001\022\022\n\nbool_value\030\005 \001(\010\032\200\003\n\016su"
    "bscription_t\022L\n\013constraints\030\001 \003(\01327.sien"
    "aplus.SienaPlusMessage.subscription_t.co"
    "nstraint_t\032\223\001\n\014constraint_t\022\014\n\004name\030\001 \002("
    "\t\022A\n\002op\030\002 \002(\01625.sienaplus.SienaPlusMessa"
    "ge.subscription_t.operator_t\0222\n\005value\030\003 "
    "\002(\0132#.sienaplus.SienaPlusMessage.value_t"
    "\"\211\001\n\noperator_t\022\t\n\005EQUAL\020\001\022\r\n\tLESS_THAN\020"
    "\002\022\020\n\014GREATER_THAN\020\003\022\n\n\006SUFFIX\020\004\022\n\n\006PREFI"
    "X\020\005\022\016\n\nSUB_STRING\020\006\022\007\n\003ANY\020\007\022\r\n\tNOT_EQUA"
    "L\020\010\022\017\n\013REGULAR_EXP\020\t\032\254\001\n\016notification_t\022"
    "I\n\tattribute\030\001 \003(\01326.sienaplus.SienaPlus"
    "Message.notification_t.attribute_t\032O\n\013at"
    "tribute_t\022\014\n\004name\030\001 \002(\t\0222\n\005value\030\002 \002(\0132#"
    ".sienaplus.SienaPlusMessage.value_t\"M\n\016m"
    "essage_type_t\022\007\n\003SUB\020\001\022\007\n\003NOT\020\002\022\t\n\005UNSUB"
    "\020\003\022\014\n\010HNDSHAKE\020\004\022\020\n\014HNDSHAKE_ACK\020\005\"E\n\nta"
    "g_type_t\022\n\n\006STRING\020\001\022\007\n\003INT\020\002\022\n\n\006DOUBLE\020"
    "\003\022\010\n\004BOOL\020\004\022\014\n\010ANY_TYPE\020\005", 1185);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "SienaPlusMessage.proto", &protobuf_RegisterTypes);
  SienaPlusMessage::default_instance_ = new SienaPlusMessage();
  SienaPlusMessage_value_t::default_instance_ = new SienaPlusMessage_value_t();
  SienaPlusMessage_subscription_t::default_instance_ = new SienaPlusMessage_subscription_t();
  SienaPlusMessage_subscription_t_constraint_t::default_instance_ = new SienaPlusMessage_subscription_t_constraint_t();
  SienaPlusMessage_notification_t::default_instance_ = new SienaPlusMessage_notification_t();
  SienaPlusMessage_notification_t_attribute_t::default_instance_ = new SienaPlusMessage_notification_t_attribute_t();
  SienaPlusMessage::default_instance_->InitAsDefaultInstance();
  SienaPlusMessage_value_t::default_instance_->InitAsDefaultInstance();
  SienaPlusMessage_subscription_t::default_instance_->InitAsDefaultInstance();
  SienaPlusMessage_subscription_t_constraint_t::default_instance_->InitAsDefaultInstance();
  SienaPlusMessage_notification_t::default_instance_->InitAsDefaultInstance();
  SienaPlusMessage_notification_t_attribute_t::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_SienaPlusMessage_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_SienaPlusMessage_2eproto {
  StaticDescriptorInitializer_SienaPlusMessage_2eproto() {
    protobuf_AddDesc_SienaPlusMessage_2eproto();
  }
} static_descriptor_initializer_SienaPlusMessage_2eproto_;


// ===================================================================

const ::google::protobuf::EnumDescriptor* SienaPlusMessage_message_type_t_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SienaPlusMessage_message_type_t_descriptor_;
}
bool SienaPlusMessage_message_type_t_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const SienaPlusMessage_message_type_t SienaPlusMessage::SUB;
const SienaPlusMessage_message_type_t SienaPlusMessage::NOT;
const SienaPlusMessage_message_type_t SienaPlusMessage::UNSUB;
const SienaPlusMessage_message_type_t SienaPlusMessage::HNDSHAKE;
const SienaPlusMessage_message_type_t SienaPlusMessage::HNDSHAKE_ACK;
const SienaPlusMessage_message_type_t SienaPlusMessage::message_type_t_MIN;
const SienaPlusMessage_message_type_t SienaPlusMessage::message_type_t_MAX;
const int SienaPlusMessage::message_type_t_ARRAYSIZE;
#endif  // _MSC_VER
const ::google::protobuf::EnumDescriptor* SienaPlusMessage_tag_type_t_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SienaPlusMessage_tag_type_t_descriptor_;
}
bool SienaPlusMessage_tag_type_t_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const SienaPlusMessage_tag_type_t SienaPlusMessage::STRING;
const SienaPlusMessage_tag_type_t SienaPlusMessage::INT;
const SienaPlusMessage_tag_type_t SienaPlusMessage::DOUBLE;
const SienaPlusMessage_tag_type_t SienaPlusMessage::BOOL;
const SienaPlusMessage_tag_type_t SienaPlusMessage::ANY_TYPE;
const SienaPlusMessage_tag_type_t SienaPlusMessage::tag_type_t_MIN;
const SienaPlusMessage_tag_type_t SienaPlusMessage::tag_type_t_MAX;
const int SienaPlusMessage::tag_type_t_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int SienaPlusMessage_value_t::kTypeFieldNumber;
const int SienaPlusMessage_value_t::kStringValueFieldNumber;
const int SienaPlusMessage_value_t::kIntValueFieldNumber;
const int SienaPlusMessage_value_t::kDoubleValueFieldNumber;
const int SienaPlusMessage_value_t::kBoolValueFieldNumber;
#endif  // !_MSC_VER

SienaPlusMessage_value_t::SienaPlusMessage_value_t()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SienaPlusMessage_value_t::InitAsDefaultInstance() {
}

SienaPlusMessage_value_t::SienaPlusMessage_value_t(const SienaPlusMessage_value_t& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SienaPlusMessage_value_t::SharedCtor() {
  _cached_size_ = 0;
  type_ = 1;
  string_value_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  int_value_ = 0;
  double_value_ = 0;
  bool_value_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SienaPlusMessage_value_t::~SienaPlusMessage_value_t() {
  SharedDtor();
}

void SienaPlusMessage_value_t::SharedDtor() {
  if (string_value_ != &::google::protobuf::internal::kEmptyString) {
    delete string_value_;
  }
  if (this != default_instance_) {
  }
}

void SienaPlusMessage_value_t::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SienaPlusMessage_value_t::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SienaPlusMessage_value_t_descriptor_;
}

const SienaPlusMessage_value_t& SienaPlusMessage_value_t::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_SienaPlusMessage_2eproto();  return *default_instance_;
}

SienaPlusMessage_value_t* SienaPlusMessage_value_t::default_instance_ = NULL;

SienaPlusMessage_value_t* SienaPlusMessage_value_t::New() const {
  return new SienaPlusMessage_value_t;
}

void SienaPlusMessage_value_t::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    type_ = 1;
    if (has_string_value()) {
      if (string_value_ != &::google::protobuf::internal::kEmptyString) {
        string_value_->clear();
      }
    }
    int_value_ = 0;
    double_value_ = 0;
    bool_value_ = false;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SienaPlusMessage_value_t::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .sienaplus.SienaPlusMessage.tag_type_t type = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::sienaplus::SienaPlusMessage_tag_type_t_IsValid(value)) {
            set_type(static_cast< ::sienaplus::SienaPlusMessage_tag_type_t >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_string_value;
        break;
      }
      
      // optional string string_value = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_string_value:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_string_value()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->string_value().data(), this->string_value().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_int_value;
        break;
      }
      
      // optional int32 int_value = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_int_value:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &int_value_)));
          set_has_int_value();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(33)) goto parse_double_value;
        break;
      }
      
      // optional double double_value = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_double_value:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &double_value_)));
          set_has_double_value();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_bool_value;
        break;
      }
      
      // optional bool bool_value = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_bool_value:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &bool_value_)));
          set_has_bool_value();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SienaPlusMessage_value_t::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .sienaplus.SienaPlusMessage.tag_type_t type = 1;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }
  
  // optional string string_value = 2;
  if (has_string_value()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->string_value().data(), this->string_value().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->string_value(), output);
  }
  
  // optional int32 int_value = 3;
  if (has_int_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->int_value(), output);
  }
  
  // optional double double_value = 4;
  if (has_double_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->double_value(), output);
  }
  
  // optional bool bool_value = 5;
  if (has_bool_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(5, this->bool_value(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SienaPlusMessage_value_t::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .sienaplus.SienaPlusMessage.tag_type_t type = 1;
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }
  
  // optional string string_value = 2;
  if (has_string_value()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->string_value().data(), this->string_value().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->string_value(), target);
  }
  
  // optional int32 int_value = 3;
  if (has_int_value()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->int_value(), target);
  }
  
  // optional double double_value = 4;
  if (has_double_value()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->double_value(), target);
  }
  
  // optional bool bool_value = 5;
  if (has_bool_value()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(5, this->bool_value(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SienaPlusMessage_value_t::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .sienaplus.SienaPlusMessage.tag_type_t type = 1;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
    }
    
    // optional string string_value = 2;
    if (has_string_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->string_value());
    }
    
    // optional int32 int_value = 3;
    if (has_int_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->int_value());
    }
    
    // optional double double_value = 4;
    if (has_double_value()) {
      total_size += 1 + 8;
    }
    
    // optional bool bool_value = 5;
    if (has_bool_value()) {
      total_size += 1 + 1;
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SienaPlusMessage_value_t::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SienaPlusMessage_value_t* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SienaPlusMessage_value_t*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SienaPlusMessage_value_t::MergeFrom(const SienaPlusMessage_value_t& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_string_value()) {
      set_string_value(from.string_value());
    }
    if (from.has_int_value()) {
      set_int_value(from.int_value());
    }
    if (from.has_double_value()) {
      set_double_value(from.double_value());
    }
    if (from.has_bool_value()) {
      set_bool_value(from.bool_value());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SienaPlusMessage_value_t::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SienaPlusMessage_value_t::CopyFrom(const SienaPlusMessage_value_t& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SienaPlusMessage_value_t::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  return true;
}

void SienaPlusMessage_value_t::Swap(SienaPlusMessage_value_t* other) {
  if (other != this) {
    std::swap(type_, other->type_);
    std::swap(string_value_, other->string_value_);
    std::swap(int_value_, other->int_value_);
    std::swap(double_value_, other->double_value_);
    std::swap(bool_value_, other->bool_value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SienaPlusMessage_value_t::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SienaPlusMessage_value_t_descriptor_;
  metadata.reflection = SienaPlusMessage_value_t_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

const ::google::protobuf::EnumDescriptor* SienaPlusMessage_subscription_t_operator_t_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SienaPlusMessage_subscription_t_operator_t_descriptor_;
}
bool SienaPlusMessage_subscription_t_operator_t_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const SienaPlusMessage_subscription_t_operator_t SienaPlusMessage_subscription_t::EQUAL;
const SienaPlusMessage_subscription_t_operator_t SienaPlusMessage_subscription_t::LESS_THAN;
const SienaPlusMessage_subscription_t_operator_t SienaPlusMessage_subscription_t::GREATER_THAN;
const SienaPlusMessage_subscription_t_operator_t SienaPlusMessage_subscription_t::SUFFIX;
const SienaPlusMessage_subscription_t_operator_t SienaPlusMessage_subscription_t::PREFIX;
const SienaPlusMessage_subscription_t_operator_t SienaPlusMessage_subscription_t::SUB_STRING;
const SienaPlusMessage_subscription_t_operator_t SienaPlusMessage_subscription_t::ANY;
const SienaPlusMessage_subscription_t_operator_t SienaPlusMessage_subscription_t::NOT_EQUAL;
const SienaPlusMessage_subscription_t_operator_t SienaPlusMessage_subscription_t::REGULAR_EXP;
const SienaPlusMessage_subscription_t_operator_t SienaPlusMessage_subscription_t::operator_t_MIN;
const SienaPlusMessage_subscription_t_operator_t SienaPlusMessage_subscription_t::operator_t_MAX;
const int SienaPlusMessage_subscription_t::operator_t_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int SienaPlusMessage_subscription_t_constraint_t::kNameFieldNumber;
const int SienaPlusMessage_subscription_t_constraint_t::kOpFieldNumber;
const int SienaPlusMessage_subscription_t_constraint_t::kValueFieldNumber;
#endif  // !_MSC_VER

SienaPlusMessage_subscription_t_constraint_t::SienaPlusMessage_subscription_t_constraint_t()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SienaPlusMessage_subscription_t_constraint_t::InitAsDefaultInstance() {
  value_ = const_cast< ::sienaplus::SienaPlusMessage_value_t*>(&::sienaplus::SienaPlusMessage_value_t::default_instance());
}

SienaPlusMessage_subscription_t_constraint_t::SienaPlusMessage_subscription_t_constraint_t(const SienaPlusMessage_subscription_t_constraint_t& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SienaPlusMessage_subscription_t_constraint_t::SharedCtor() {
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  op_ = 1;
  value_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SienaPlusMessage_subscription_t_constraint_t::~SienaPlusMessage_subscription_t_constraint_t() {
  SharedDtor();
}

void SienaPlusMessage_subscription_t_constraint_t::SharedDtor() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (this != default_instance_) {
    delete value_;
  }
}

void SienaPlusMessage_subscription_t_constraint_t::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SienaPlusMessage_subscription_t_constraint_t::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SienaPlusMessage_subscription_t_constraint_t_descriptor_;
}

const SienaPlusMessage_subscription_t_constraint_t& SienaPlusMessage_subscription_t_constraint_t::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_SienaPlusMessage_2eproto();  return *default_instance_;
}

SienaPlusMessage_subscription_t_constraint_t* SienaPlusMessage_subscription_t_constraint_t::default_instance_ = NULL;

SienaPlusMessage_subscription_t_constraint_t* SienaPlusMessage_subscription_t_constraint_t::New() const {
  return new SienaPlusMessage_subscription_t_constraint_t;
}

void SienaPlusMessage_subscription_t_constraint_t::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
      }
    }
    op_ = 1;
    if (has_value()) {
      if (value_ != NULL) value_->::sienaplus::SienaPlusMessage_value_t::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SienaPlusMessage_subscription_t_constraint_t::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_op;
        break;
      }
      
      // required .sienaplus.SienaPlusMessage.subscription_t.operator_t op = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_op:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::sienaplus::SienaPlusMessage_subscription_t_operator_t_IsValid(value)) {
            set_op(static_cast< ::sienaplus::SienaPlusMessage_subscription_t_operator_t >(value));
          } else {
            mutable_unknown_fields()->AddVarint(2, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_value;
        break;
      }
      
      // required .sienaplus.SienaPlusMessage.value_t value = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_value:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_value()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SienaPlusMessage_subscription_t_constraint_t::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(), output);
  }
  
  // required .sienaplus.SienaPlusMessage.subscription_t.operator_t op = 2;
  if (has_op()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->op(), output);
  }
  
  // required .sienaplus.SienaPlusMessage.value_t value = 3;
  if (has_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->value(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SienaPlusMessage_subscription_t_constraint_t::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }
  
  // required .sienaplus.SienaPlusMessage.subscription_t.operator_t op = 2;
  if (has_op()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->op(), target);
  }
  
  // required .sienaplus.SienaPlusMessage.value_t value = 3;
  if (has_value()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->value(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SienaPlusMessage_subscription_t_constraint_t::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }
    
    // required .sienaplus.SienaPlusMessage.subscription_t.operator_t op = 2;
    if (has_op()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->op());
    }
    
    // required .sienaplus.SienaPlusMessage.value_t value = 3;
    if (has_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->value());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SienaPlusMessage_subscription_t_constraint_t::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SienaPlusMessage_subscription_t_constraint_t* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SienaPlusMessage_subscription_t_constraint_t*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SienaPlusMessage_subscription_t_constraint_t::MergeFrom(const SienaPlusMessage_subscription_t_constraint_t& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_op()) {
      set_op(from.op());
    }
    if (from.has_value()) {
      mutable_value()->::sienaplus::SienaPlusMessage_value_t::MergeFrom(from.value());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SienaPlusMessage_subscription_t_constraint_t::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SienaPlusMessage_subscription_t_constraint_t::CopyFrom(const SienaPlusMessage_subscription_t_constraint_t& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SienaPlusMessage_subscription_t_constraint_t::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;
  
  if (has_value()) {
    if (!this->value().IsInitialized()) return false;
  }
  return true;
}

void SienaPlusMessage_subscription_t_constraint_t::Swap(SienaPlusMessage_subscription_t_constraint_t* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    std::swap(op_, other->op_);
    std::swap(value_, other->value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SienaPlusMessage_subscription_t_constraint_t::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SienaPlusMessage_subscription_t_constraint_t_descriptor_;
  metadata.reflection = SienaPlusMessage_subscription_t_constraint_t_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int SienaPlusMessage_subscription_t::kConstraintsFieldNumber;
#endif  // !_MSC_VER

SienaPlusMessage_subscription_t::SienaPlusMessage_subscription_t()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SienaPlusMessage_subscription_t::InitAsDefaultInstance() {
}

SienaPlusMessage_subscription_t::SienaPlusMessage_subscription_t(const SienaPlusMessage_subscription_t& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SienaPlusMessage_subscription_t::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SienaPlusMessage_subscription_t::~SienaPlusMessage_subscription_t() {
  SharedDtor();
}

void SienaPlusMessage_subscription_t::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SienaPlusMessage_subscription_t::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SienaPlusMessage_subscription_t::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SienaPlusMessage_subscription_t_descriptor_;
}

const SienaPlusMessage_subscription_t& SienaPlusMessage_subscription_t::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_SienaPlusMessage_2eproto();  return *default_instance_;
}

SienaPlusMessage_subscription_t* SienaPlusMessage_subscription_t::default_instance_ = NULL;

SienaPlusMessage_subscription_t* SienaPlusMessage_subscription_t::New() const {
  return new SienaPlusMessage_subscription_t;
}

void SienaPlusMessage_subscription_t::Clear() {
  constraints_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SienaPlusMessage_subscription_t::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .sienaplus.SienaPlusMessage.subscription_t.constraint_t constraints = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_constraints:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_constraints()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_constraints;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SienaPlusMessage_subscription_t::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .sienaplus.SienaPlusMessage.subscription_t.constraint_t constraints = 1;
  for (int i = 0; i < this->constraints_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->constraints(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SienaPlusMessage_subscription_t::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .sienaplus.SienaPlusMessage.subscription_t.constraint_t constraints = 1;
  for (int i = 0; i < this->constraints_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->constraints(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SienaPlusMessage_subscription_t::ByteSize() const {
  int total_size = 0;
  
  // repeated .sienaplus.SienaPlusMessage.subscription_t.constraint_t constraints = 1;
  total_size += 1 * this->constraints_size();
  for (int i = 0; i < this->constraints_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->constraints(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SienaPlusMessage_subscription_t::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SienaPlusMessage_subscription_t* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SienaPlusMessage_subscription_t*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SienaPlusMessage_subscription_t::MergeFrom(const SienaPlusMessage_subscription_t& from) {
  GOOGLE_CHECK_NE(&from, this);
  constraints_.MergeFrom(from.constraints_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SienaPlusMessage_subscription_t::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SienaPlusMessage_subscription_t::CopyFrom(const SienaPlusMessage_subscription_t& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SienaPlusMessage_subscription_t::IsInitialized() const {
  
  for (int i = 0; i < constraints_size(); i++) {
    if (!this->constraints(i).IsInitialized()) return false;
  }
  return true;
}

void SienaPlusMessage_subscription_t::Swap(SienaPlusMessage_subscription_t* other) {
  if (other != this) {
    constraints_.Swap(&other->constraints_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SienaPlusMessage_subscription_t::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SienaPlusMessage_subscription_t_descriptor_;
  metadata.reflection = SienaPlusMessage_subscription_t_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int SienaPlusMessage_notification_t_attribute_t::kNameFieldNumber;
const int SienaPlusMessage_notification_t_attribute_t::kValueFieldNumber;
#endif  // !_MSC_VER

SienaPlusMessage_notification_t_attribute_t::SienaPlusMessage_notification_t_attribute_t()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SienaPlusMessage_notification_t_attribute_t::InitAsDefaultInstance() {
  value_ = const_cast< ::sienaplus::SienaPlusMessage_value_t*>(&::sienaplus::SienaPlusMessage_value_t::default_instance());
}

SienaPlusMessage_notification_t_attribute_t::SienaPlusMessage_notification_t_attribute_t(const SienaPlusMessage_notification_t_attribute_t& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SienaPlusMessage_notification_t_attribute_t::SharedCtor() {
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  value_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SienaPlusMessage_notification_t_attribute_t::~SienaPlusMessage_notification_t_attribute_t() {
  SharedDtor();
}

void SienaPlusMessage_notification_t_attribute_t::SharedDtor() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (this != default_instance_) {
    delete value_;
  }
}

void SienaPlusMessage_notification_t_attribute_t::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SienaPlusMessage_notification_t_attribute_t::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SienaPlusMessage_notification_t_attribute_t_descriptor_;
}

const SienaPlusMessage_notification_t_attribute_t& SienaPlusMessage_notification_t_attribute_t::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_SienaPlusMessage_2eproto();  return *default_instance_;
}

SienaPlusMessage_notification_t_attribute_t* SienaPlusMessage_notification_t_attribute_t::default_instance_ = NULL;

SienaPlusMessage_notification_t_attribute_t* SienaPlusMessage_notification_t_attribute_t::New() const {
  return new SienaPlusMessage_notification_t_attribute_t;
}

void SienaPlusMessage_notification_t_attribute_t::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
      }
    }
    if (has_value()) {
      if (value_ != NULL) value_->::sienaplus::SienaPlusMessage_value_t::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SienaPlusMessage_notification_t_attribute_t::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_value;
        break;
      }
      
      // required .sienaplus.SienaPlusMessage.value_t value = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_value:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_value()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SienaPlusMessage_notification_t_attribute_t::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(), output);
  }
  
  // required .sienaplus.SienaPlusMessage.value_t value = 2;
  if (has_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->value(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SienaPlusMessage_notification_t_attribute_t::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }
  
  // required .sienaplus.SienaPlusMessage.value_t value = 2;
  if (has_value()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->value(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SienaPlusMessage_notification_t_attribute_t::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }
    
    // required .sienaplus.SienaPlusMessage.value_t value = 2;
    if (has_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->value());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SienaPlusMessage_notification_t_attribute_t::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SienaPlusMessage_notification_t_attribute_t* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SienaPlusMessage_notification_t_attribute_t*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SienaPlusMessage_notification_t_attribute_t::MergeFrom(const SienaPlusMessage_notification_t_attribute_t& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_value()) {
      mutable_value()->::sienaplus::SienaPlusMessage_value_t::MergeFrom(from.value());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SienaPlusMessage_notification_t_attribute_t::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SienaPlusMessage_notification_t_attribute_t::CopyFrom(const SienaPlusMessage_notification_t_attribute_t& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SienaPlusMessage_notification_t_attribute_t::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  
  if (has_value()) {
    if (!this->value().IsInitialized()) return false;
  }
  return true;
}

void SienaPlusMessage_notification_t_attribute_t::Swap(SienaPlusMessage_notification_t_attribute_t* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    std::swap(value_, other->value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SienaPlusMessage_notification_t_attribute_t::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SienaPlusMessage_notification_t_attribute_t_descriptor_;
  metadata.reflection = SienaPlusMessage_notification_t_attribute_t_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int SienaPlusMessage_notification_t::kAttributeFieldNumber;
#endif  // !_MSC_VER

SienaPlusMessage_notification_t::SienaPlusMessage_notification_t()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SienaPlusMessage_notification_t::InitAsDefaultInstance() {
}

SienaPlusMessage_notification_t::SienaPlusMessage_notification_t(const SienaPlusMessage_notification_t& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SienaPlusMessage_notification_t::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SienaPlusMessage_notification_t::~SienaPlusMessage_notification_t() {
  SharedDtor();
}

void SienaPlusMessage_notification_t::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SienaPlusMessage_notification_t::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SienaPlusMessage_notification_t::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SienaPlusMessage_notification_t_descriptor_;
}

const SienaPlusMessage_notification_t& SienaPlusMessage_notification_t::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_SienaPlusMessage_2eproto();  return *default_instance_;
}

SienaPlusMessage_notification_t* SienaPlusMessage_notification_t::default_instance_ = NULL;

SienaPlusMessage_notification_t* SienaPlusMessage_notification_t::New() const {
  return new SienaPlusMessage_notification_t;
}

void SienaPlusMessage_notification_t::Clear() {
  attribute_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SienaPlusMessage_notification_t::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .sienaplus.SienaPlusMessage.notification_t.attribute_t attribute = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_attribute:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_attribute()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_attribute;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SienaPlusMessage_notification_t::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .sienaplus.SienaPlusMessage.notification_t.attribute_t attribute = 1;
  for (int i = 0; i < this->attribute_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->attribute(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SienaPlusMessage_notification_t::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .sienaplus.SienaPlusMessage.notification_t.attribute_t attribute = 1;
  for (int i = 0; i < this->attribute_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->attribute(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SienaPlusMessage_notification_t::ByteSize() const {
  int total_size = 0;
  
  // repeated .sienaplus.SienaPlusMessage.notification_t.attribute_t attribute = 1;
  total_size += 1 * this->attribute_size();
  for (int i = 0; i < this->attribute_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->attribute(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SienaPlusMessage_notification_t::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SienaPlusMessage_notification_t* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SienaPlusMessage_notification_t*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SienaPlusMessage_notification_t::MergeFrom(const SienaPlusMessage_notification_t& from) {
  GOOGLE_CHECK_NE(&from, this);
  attribute_.MergeFrom(from.attribute_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SienaPlusMessage_notification_t::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SienaPlusMessage_notification_t::CopyFrom(const SienaPlusMessage_notification_t& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SienaPlusMessage_notification_t::IsInitialized() const {
  
  for (int i = 0; i < attribute_size(); i++) {
    if (!this->attribute(i).IsInitialized()) return false;
  }
  return true;
}

void SienaPlusMessage_notification_t::Swap(SienaPlusMessage_notification_t* other) {
  if (other != this) {
    attribute_.Swap(&other->attribute_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SienaPlusMessage_notification_t::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SienaPlusMessage_notification_t_descriptor_;
  metadata.reflection = SienaPlusMessage_notification_t_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int SienaPlusMessage::kTypeFieldNumber;
const int SienaPlusMessage::kSenderFieldNumber;
const int SienaPlusMessage::kSubscriptionFieldNumber;
const int SienaPlusMessage::kNotificationFieldNumber;
const int SienaPlusMessage::kUnsubscriptionFieldNumber;
const int SienaPlusMessage::kPayloadFieldNumber;
const int SienaPlusMessage::kAssignedIdFieldNumber;
#endif  // !_MSC_VER

SienaPlusMessage::SienaPlusMessage()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SienaPlusMessage::InitAsDefaultInstance() {
  subscription_ = const_cast< ::sienaplus::SienaPlusMessage_subscription_t*>(&::sienaplus::SienaPlusMessage_subscription_t::default_instance());
  notification_ = const_cast< ::sienaplus::SienaPlusMessage_notification_t*>(&::sienaplus::SienaPlusMessage_notification_t::default_instance());
}

SienaPlusMessage::SienaPlusMessage(const SienaPlusMessage& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SienaPlusMessage::SharedCtor() {
  _cached_size_ = 0;
  type_ = 1;
  sender_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  subscription_ = NULL;
  notification_ = NULL;
  unsubscription_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  payload_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  assigned_id_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SienaPlusMessage::~SienaPlusMessage() {
  SharedDtor();
}

void SienaPlusMessage::SharedDtor() {
  if (sender_ != &::google::protobuf::internal::kEmptyString) {
    delete sender_;
  }
  if (unsubscription_ != &::google::protobuf::internal::kEmptyString) {
    delete unsubscription_;
  }
  if (payload_ != &::google::protobuf::internal::kEmptyString) {
    delete payload_;
  }
  if (this != default_instance_) {
    delete subscription_;
    delete notification_;
  }
}

void SienaPlusMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SienaPlusMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SienaPlusMessage_descriptor_;
}

const SienaPlusMessage& SienaPlusMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_SienaPlusMessage_2eproto();  return *default_instance_;
}

SienaPlusMessage* SienaPlusMessage::default_instance_ = NULL;

SienaPlusMessage* SienaPlusMessage::New() const {
  return new SienaPlusMessage;
}

void SienaPlusMessage::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    type_ = 1;
    if (has_sender()) {
      if (sender_ != &::google::protobuf::internal::kEmptyString) {
        sender_->clear();
      }
    }
    if (has_subscription()) {
      if (subscription_ != NULL) subscription_->::sienaplus::SienaPlusMessage_subscription_t::Clear();
    }
    if (has_notification()) {
      if (notification_ != NULL) notification_->::sienaplus::SienaPlusMessage_notification_t::Clear();
    }
    if (has_unsubscription()) {
      if (unsubscription_ != &::google::protobuf::internal::kEmptyString) {
        unsubscription_->clear();
      }
    }
    if (has_payload()) {
      if (payload_ != &::google::protobuf::internal::kEmptyString) {
        payload_->clear();
      }
    }
    assigned_id_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SienaPlusMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .sienaplus.SienaPlusMessage.message_type_t type = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::sienaplus::SienaPlusMessage_message_type_t_IsValid(value)) {
            set_type(static_cast< ::sienaplus::SienaPlusMessage_message_type_t >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_sender;
        break;
      }
      
      // required string sender = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_sender:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_sender()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->sender().data(), this->sender().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_subscription;
        break;
      }
      
      // optional .sienaplus.SienaPlusMessage.subscription_t subscription = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_subscription:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_subscription()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_notification;
        break;
      }
      
      // optional .sienaplus.SienaPlusMessage.notification_t notification = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_notification:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_notification()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_unsubscription;
        break;
      }
      
      // optional string unsubscription = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_unsubscription:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_unsubscription()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->unsubscription().data(), this->unsubscription().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(50)) goto parse_payload;
        break;
      }
      
      // optional string payload = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_payload:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_payload()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->payload().data(), this->payload().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(56)) goto parse_assigned_id;
        break;
      }
      
      // optional int32 assigned_id = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_assigned_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &assigned_id_)));
          set_has_assigned_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SienaPlusMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .sienaplus.SienaPlusMessage.message_type_t type = 1;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }
  
  // required string sender = 2;
  if (has_sender()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->sender().data(), this->sender().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->sender(), output);
  }
  
  // optional .sienaplus.SienaPlusMessage.subscription_t subscription = 3;
  if (has_subscription()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->subscription(), output);
  }
  
  // optional .sienaplus.SienaPlusMessage.notification_t notification = 4;
  if (has_notification()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->notification(), output);
  }
  
  // optional string unsubscription = 5;
  if (has_unsubscription()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->unsubscription().data(), this->unsubscription().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      5, this->unsubscription(), output);
  }
  
  // optional string payload = 6;
  if (has_payload()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->payload().data(), this->payload().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      6, this->payload(), output);
  }
  
  // optional int32 assigned_id = 7;
  if (has_assigned_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->assigned_id(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SienaPlusMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .sienaplus.SienaPlusMessage.message_type_t type = 1;
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }
  
  // required string sender = 2;
  if (has_sender()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->sender().data(), this->sender().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->sender(), target);
  }
  
  // optional .sienaplus.SienaPlusMessage.subscription_t subscription = 3;
  if (has_subscription()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->subscription(), target);
  }
  
  // optional .sienaplus.SienaPlusMessage.notification_t notification = 4;
  if (has_notification()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->notification(), target);
  }
  
  // optional string unsubscription = 5;
  if (has_unsubscription()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->unsubscription().data(), this->unsubscription().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->unsubscription(), target);
  }
  
  // optional string payload = 6;
  if (has_payload()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->payload().data(), this->payload().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->payload(), target);
  }
  
  // optional int32 assigned_id = 7;
  if (has_assigned_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(7, this->assigned_id(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SienaPlusMessage::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .sienaplus.SienaPlusMessage.message_type_t type = 1;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
    }
    
    // required string sender = 2;
    if (has_sender()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->sender());
    }
    
    // optional .sienaplus.SienaPlusMessage.subscription_t subscription = 3;
    if (has_subscription()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->subscription());
    }
    
    // optional .sienaplus.SienaPlusMessage.notification_t notification = 4;
    if (has_notification()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->notification());
    }
    
    // optional string unsubscription = 5;
    if (has_unsubscription()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->unsubscription());
    }
    
    // optional string payload = 6;
    if (has_payload()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->payload());
    }
    
    // optional int32 assigned_id = 7;
    if (has_assigned_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->assigned_id());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SienaPlusMessage::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SienaPlusMessage* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SienaPlusMessage*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SienaPlusMessage::MergeFrom(const SienaPlusMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_sender()) {
      set_sender(from.sender());
    }
    if (from.has_subscription()) {
      mutable_subscription()->::sienaplus::SienaPlusMessage_subscription_t::MergeFrom(from.subscription());
    }
    if (from.has_notification()) {
      mutable_notification()->::sienaplus::SienaPlusMessage_notification_t::MergeFrom(from.notification());
    }
    if (from.has_unsubscription()) {
      set_unsubscription(from.unsubscription());
    }
    if (from.has_payload()) {
      set_payload(from.payload());
    }
    if (from.has_assigned_id()) {
      set_assigned_id(from.assigned_id());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SienaPlusMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SienaPlusMessage::CopyFrom(const SienaPlusMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SienaPlusMessage::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  
  if (has_subscription()) {
    if (!this->subscription().IsInitialized()) return false;
  }
  if (has_notification()) {
    if (!this->notification().IsInitialized()) return false;
  }
  return true;
}

void SienaPlusMessage::Swap(SienaPlusMessage* other) {
  if (other != this) {
    std::swap(type_, other->type_);
    std::swap(sender_, other->sender_);
    std::swap(subscription_, other->subscription_);
    std::swap(notification_, other->notification_);
    std::swap(unsubscription_, other->unsubscription_);
    std::swap(payload_, other->payload_);
    std::swap(assigned_id_, other->assigned_id_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SienaPlusMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SienaPlusMessage_descriptor_;
  metadata.reflection = SienaPlusMessage_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace sienaplus

// @@protoc_insertion_point(global_scope)
